// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.gvnix.geo.component.domain;

import javax.persistence.Entity;
import org.gvnix.geo.component.domain.Vet;

privileged aspect Vet_Roo_Jpa_Entity {
    
    declare @type: Vet: @Entity;
    
}
