// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.gvnix.geo.component.domain;

import org.gvnix.geo.component.domain.Visit;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Visit_Roo_Configurable {
    
    declare @type: Visit: @Configurable;
    
}
