= gvNIX quick start Repository application
Getting started with gvNIX
:page-layout: base
:toc-placement: manual
:homepage: http://gvnix.org
:download: http://projects.spring.io/spring-roo/#running-from-shell
:installguide: https://github.com/DISID/gvnix-samples/blob/master/INSTALL-gvNIX-2.x.adoc
:download: http://projects.spring.io/spring-roo/#running-from-shell

gvNIX is a Spring Roo distribution that focuses both enterprise knowledge and 
enterprise standards to build Java applications.

If you don't know _What is gvNIX?_ you should start with https://github.com/DISID/gvnix-samples/tree/master/quickstart-app[quickstart-app] tutorial.

You must {download}[download], unpack and {installguide}[install] the 
development environment for gvNIX 2.0.0.M1, to be able to follow this guide.

The goal of this quick start repository app guide is to familiarize you with how the repository and service layers are generated using gvNIX.
For this purpose, we will build a simple application. This process includes the creation of an entity model, repository and service layer setup, web views generation, and finally we show how to setup <<create-patterns-and-details-using-datatables, Datatables>> and <<loupe-fields, Loupe fields>> to work with the repository layer.

The application presented in this guide is the Spring PetClinic application. The users of the application are employees of the clinic who, in the course of their work, need to view and manage information regarding veterinarians, the clients, and their pets.

Note this sample isn’t a real application which normally needs additional work like UI customization, performance improvement, database queries tunning, etc.

//You can see an example of a *generated repository web application* using gvNIX
//http://repository-gvnix.rhcloud.com/login[here] (*user*: admin | *pass*: admin)

== Run from Git

If you want to preview this sample application, follow this steps on the following order. If you prefer to develop by your own, go to https://github.com/DISID/gvnix-samples/tree/master/quickstart-repository-app#build-your-own-repository-app[gvNIX Repository Guide]

- Clone github repository
[source, shell]
$ git clone https://github.com/DISID/gvnix-samples.git

- Also, you can download the https://github.com/DISID/gvnix-samples/archive/master.zip[project source files] compressed in zip format.

- Acces to quickstart-repository-app
[source, shell]
$ cd gvnix-samples/quickstart-repository-app

- Execute application using maven:
[source, shell]
$ mvn clean compile tomcat7:run

- Open your browser on http://localhost:8080/petclinic/
- Access using _admin_ as username and _admin_ as password.

== Build your own app 	
 	
You can execute https://github.com/DISID/gvnix-samples/blob/master/quickstart-repository-app/quickstart-repository.roo[quickstart-repository.roo] file and creates a petclinic example application with both service and repository layers. 	
 	
You can follow the instructions below to create a project with repository layers and services. If you don't have experience using gvNIX, you can familiarize with it by following https://github.com/DISID/gvnix-samples/tree/master/quickstart-app#build-your-own-app[quickstart-app guide]. 
 	
This guide teaches you how to: 	

. <<create-a-new-project, Create a new project>>
. <<persistence-setup, Persistence Setup>>
. <<build-the-domain-model, Build the domain model>>
. <<generate-repository-layer, Generate Repository Layer>> 	
. <<generate-services, Generate Service Layer>> 
. <<web-layers, Generate Web Layer>>
. <<jquery-datatables-and-bootstrap-setup, JQuery Datatables and Bootstrap Setup >>
. <<list-views-with-datatables, List views with Datatables>>
. <<loupe-fields, Loupe Components >>	
. <<configure-datatables-and-loupes, Configure Datatables And Loupes >> 
. <<more-roo-functionalities, Other Roo features included in this sample >>
. <<more-gvnix-functionalities, Other gvNIX features included in this sample>>

[[create-a-new-project]]
== Create a new project

. Create a directory for the new project.
+

[source,shell]
$ mkdir clinic
$ cd clinic

. Start gvNIX
. Execute command to create project:
+

[source,shell]
project setup --topLevelPackage com.springsource.petclinic --projectName petclinic


[[persistence-setup]]
== Persistence Setup

Execute the following command to set up persistence in your gvNIX project:

[source,shell]
jpa setup --provider HIBERNATE --database HYPERSONIC_PERSISTENT

NOTE: _You can replace *provider* param and *database* param with your own configuration._

[[build-the-domain-model]]
== Build the domain model

=== Create the domain entities

. Create entities:
+
By default Spring Roo uses Active record-style JPA Entities. To opt out of the default Active Record style, you have to create your entities with the activeRecord option set to false.
+
[source,shell]
entity jpa --class ~.domain.Pet --activeRecord false
entity jpa --class ~.domain.Visit --activeRecord false
entity jpa --class ~.domain.Vet --activeRecord false
entity jpa --class ~.domain.Owner --activeRecord false
entity jpa --class ~.domain.AbstractPerson --activeRecord false
+
NOTE: _This will add the @RooJpaEntity notation to your entities insted of the @RooJpaActiveRecord notation._

. Create *PetType* and *Specialty* enumerates to use in petclinic application:
+

[source,shell]
enum type --class ~.reference.PetType
enum constant --name Dog
enum constant --name Cat
enum constant --name Bird
enum type --class ~.reference.Specialty
enum constant --name Cardiology
enum constant --name Dentistry
enum constant --name Nutrition

. Add fields to entities:
+

[source,shell]
field string --fieldName firstName --sizeMin 3 --sizeMax 30 --class ~.domain.AbstractPerson
field string --fieldName lastName --notNull --sizeMin 3 --sizeMax 30
field string --fieldName address --notNull --sizeMax 50 --sizeMin 1
field string --fieldName city --notNull --sizeMax 30
field string --fieldName telephone --notNull
field string --fieldName homePage --sizeMax 30
field string --fieldName email --sizeMax 30 --sizeMin 6
field date --fieldName birthDay --type java.util.Date --notNull
field string --fieldName description --sizeMax 255 --class ~.domain.Visit
field date --fieldName visitDate --type java.util.Date --notNull --past
field reference --fieldName pet --type ~.domain.Pet --notNull
field reference --fieldName vet --type ~.domain.Vet
field boolean --fieldName sendReminders --notNull --primitive --class ~.domain.Pet
field string --fieldName name --notNull --sizeMin 1
field number --fieldName weight --type java.lang.Float --notNull --min 0
field reference --fieldName owner --type ~.domain.Owner
field enum --fieldName type --type ~.reference.PetType --notNull
field date --fieldName employedSince --type java.util.Calendar --notNull --past --class ~.domain.Vet
field enum --fieldName specialty --type ~.reference.Specialty --notNull false
field set --class ~.domain.Owner --fieldName pets --type ~.domain.Pet --mappedBy owner --notNull false --cardinality ONE_TO_MANY
field set --class ~.domain.Vet --fieldName visits --type ~.domain.Visit --mappedBy vet --notNull false --cardinality ONE_TO_MANY
field reference --fieldName owner --type ~.domain.Owner --class ~.domain.Vet
field set --fieldName vets --type ~.domain.Vet --class ~.domain.Owner --cardinality ONE_TO_MANY --mappedBy owner
field set --fieldName visits --type ~.domain.Visit --class ~.domain.Pet --cardinality ONE_TO_MANY --mappedBy pet

 	
[[generate-repository-layer]] 	
== Generate Repository Layer
 	
Now, you can add the repository layers to your entities. To generate them you have to run the next commands:
	
[source, shell]
repository jpa --interface ~.repository.PetRepository --entity ~.domain.Pet
repository jpa --interface ~.repository.VisitRepository --entity ~.domain.Visit
repository jpa --interface ~.repository.AbstractPersonRepository --entity ~.domain.AbstractPerson
repository jpa --interface ~.repository.VetRepository --entity ~.domain.Vet
repository jpa --interface ~.repository.OwnerRepository --entity ~.domain.Owner

 	
[[generate-services]] 	
== Generate Service Layer	
 	
You can include a service layer in your application. It will expose the CRUD functionality provided by this persistence layer through its interface and implementation. 
To create a service layer for each entity you have to execute the next command, which creates an interface and an implementation of the services: 
	
[source, shell]
service type --interface ~.service.PetService --entity ~.domain.Pet
service type --interface ~.service.VisitService --entity ~.domain.Visit
service type --interface ~.service.AbstractPersonService --entity ~.domain.AbstractPerson
service type --interface ~.service.VetService --entity ~.domain.Vet
service type --interface ~.service.OwnerService --entity ~.domain.Owner

If a persistence-providing layer such as Roo's default entity layer or a repository layer is present for a given domain entity, the service layer will expose the CRUD functionality provided by this persistence layer through its interface and implementation.
In your case, the service layer will call to the repository layer.

[[web-layers]]
== Generate Web Layer

. Execute the following commands setup web layer and generate web layer:
+

[source,shell]
web mvc setup

. Execute the following command to generate CRUD views for all application entities:
+

[source,shell]
web mvc all --package ~.web


[[jquery-datatables-and-bootstrap-setup]]
== JQuery, Datatables & Bootstrap Setup

=== JQuery

. To use jQuery components in your project, you must to execute the following command:
+

[source,shell]
web mvc jquery setup

. Configure all your views to use jQuery components running the next command:
+

[source,shell]
web mvc jquery all

. Optionally, you can convert view-by-view to jQuery
+

[source,shell]
web mvc jquery add --type ~.web.PetController

=== Datatables

To activate the http://dandelion.github.io/components/datatables/[Datatables] feature on project, execute the following command:

[source,shell]
web mvc datatables setup 

=== Bootstrap

To activate Bootstrap style on application pages execute the next command:

[source,shell]
web mvc bootstrap setup

[[list-views-with-datatables]] 
== List views with Datatables

=== Improve List views

After setup Datatables components run the following commands to improve list views with Datatables components:

[source,shell]
web mvc datatables add --type ~.web.VetController --mode show
web mvc datatables add --type ~.web.PetController
web mvc datatables add --type ~.web.OwnerController
web mvc datatables add --type ~.web.VisitController  --ajax true


NOTE: _Use *--mode* param with show value, to display only a record per page_. 

=== Include ToMany relationships inside List views (Master-details pattern)

After create Datatables master patterns, you can add detail list views which represent ToMany relationships with other entities.

[source,shell]
web mvc datatables detail add --type ~.web.OwnerController --property pets
web mvc datatables detail add --type ~.web.OwnerController --property vets
web mvc datatables detail add --type ~.web.PetController --property visits
web mvc datatables detail add --type ~.web.VetController --property visits

[[loupe-fields]]
== Loupe Fields

The Loupe fields provide new functionality to handle ToOne relationship more easily than using combobox.

To implement Loupe fields in your gvNIX application you need to execute the following commands:

. Setup Loupe components:
+

[source,shell]
web mvc loupe setup

. Add some necessary functions to the controller:
+

[source,shell]
web mvc loupe set --controller ~.web.VisitController

. Convert related fields to loupe elements on create and update views:
+

[source,shell]
web mvc loupe field --controller ~.web.VisitController --field pet --caption name --additionalFields name,weight --max 5
web mvc loupe field --controller ~.web.VisitController --field vet

NOTE: _You can configure callbacks functions for fields above editing 'scripts/loupefield/loupe-callbacks.js'. You can add onDraw function and onSet function to manage that events._

[[configure-datatables-and-loupes]] 	
== Configure Datatables And Loupes

Datatables and Loupe fields need to access to an entity manager to execute the required search on database. But, if you use a repository layer, the entitity manager is not avaliable by default. To solve this problem you have to follow this steps:

. Create a RepositoryCustom class in the repository package, using this code:
+
[source,java]
public interface RepositoryCustom {
  public abstract EntityManager getEntityManager();
}
 	
. Create a EntityManagerProviderImpl class which implements EntityManagerProvider in the web package, using this code:
+
[source,java]
public class EntityManagerProviderImpl implements EntityManagerProvider {
	private @Autowired ListableBeanFactory listableBeanFactory;
	public EntityManager getEntityManager(Class klass) {
	    try {
	      Repositories repositories = new Repositories(listableBeanFactory);
	      Object r = repositories.getRepositoryFor(klass);
	      Method[] methods = r.getClass().getDeclaredMethods();
	        for (Method method : methods) {
	                if (method.getReturnType() == EntityManager.class) {
	                    method.setAccessible(true);
	                    return (EntityManager) method.invoke(r, null);
	                }
	        }
	    }
	    catch (Exception e) {
	        throw new IllegalStateException(
	                "Error getting entity manager for domain class: ".concat(klass.getName()), e);
	    }
	    throw new IllegalStateException(
	            "Cannot get entity manager for domain class: ".concat(klass.getName()));
	}
}

. You have to register the correct entityManagerProvider. To do this, in the /petclinic/src/main/webapp/WEB-INF/spring/webmvc-config.xml file you have to change the class propiety value of the entityManagerProvider bean by the EntityManagerProviderImpl location. The resulting bean will be:
+
[source,xml]
<bean class="com.springsource.petclinic.web.EntityManagerProviderImpl" id="entityManagerProvider"/>

. Change your repository interfaces to make them extend RepositoryCustom:
+
[source,java]
public interface VetRepository extends RepositoryCustom{}
+
[source,java]
public interface VisitRepository extends RepositoryCustom{}
+
[source,java]
public interface PetRepository extends RepositoryCustom{}
+
[source,java]
public interface OwnerRepository extends RepositoryCustom{}
+
[source,java]
public interface AbstractPersonRepository extends RepositoryCustom {}

. Create a repository implementation class in the repository package, for every repository interface. These classes extend RepositoryCustom and contain the next code:
+
[source,java]
public class XXRepositoryImpl implements RepositoryCustom{
    @PersistenceContext
    private EntityManager em;
    public EntityManager getEntityManager() {
      return em;
    }
}
+
====
*Example*

[source,java]
public class VisitRepositoryImpl implements RepositoryCustom{
    @PersistenceContext
    private EntityManager em;
    public EntityManager getEntityManager() {
      return em;
    }
}
====

[[more-roo-functionalities]] 	
== Other Roo features included in this sample

This project is a simplified version of the project created by executing https://github.com/DISID/gvnix-samples/blob/master/quickstart-repository-app/quickstart-repository.roo[quickstart-repository.roo] file. It, also, includes the next http://projects.spring.io/spring-roo/[Spring Roo] functionalities:

. https://github.com/DISID/gvnix-samples/tree/master/quickstart-app#finder-methods[Finder methodes]

. https://github.com/DISID/gvnix-samples/tree/master/quickstart-app#spring-security[Security]

. https://github.com/DISID/gvnix-samples/tree/master/quickstart-app#junit-and-selenium-tests[JUnit and Selenium Tests] 


[[more-gvnix-functionalities]] 	
== Other gvNIX features included in this sample

This project is a simplified version of the project created by executing https://github.com/DISID/gvnix-samples/blob/master/quickstart-repository-app/quickstart-repository.roo[quickstart-repository.roo] file. It includes the next gvNIX functionalities:

. https://github.com/DISID/gvnix-samples/tree/master/quickstart-app#menu-setup[Menu Setup]

. https://github.com/DISID/gvnix-samples/tree/master/quickstart-app#optimistic-concurrency-control[Optimistic Concurrency Control]

. https://github.com/DISID/gvnix-samples/tree/master/quickstart-app#webservices[WebServices] 



== Related libraries, projects, etc..

gvNIX is based on https://github.com/spring-projects/spring-roo[Spring Roo] project. 

http://docs.spring.io/autorepo/docs/spring-roo/1.3.1.RELEASE/reference/html/base-layers.html[Spring Repository Documentation]

http://dandelion.github.io/components/datatables/[Dandelion Datatables]
