= gvNIX quick start Repository application
Getting started with gvNIX
:page-layout: base
:toc-placement: manual
:homepage: http://gvnix.org
:download: http://sourceforge.net/projects/gvnix/
:installguide: https://github.com/DISID/gvnix-samples/blob/master/INSTALL-gvNIX.adoc
:download: http://sourceforge.net/projects/gvnix/

gvNIX is a Spring Roo distribution that focuses both enterprise knowledge and 
enterprise standards to build Java applications.

If you don't know _What is gvNIX?_ you should start with https://github.com/DISID/gvnix-samples/tree/master/quickstart-app[quickstart-app] tutorial.

You must {download}[download], unpack and {installguide}[install] the 
development environment for gvNIX 1.5+, to be able to follow this guide.

The goal of this quick start repository app guide is to familiarize you with repository apps generated using gvNIX. For this 
purpose, we will build an application based on https://github.com/DISID/gvnix-samples/tree/master/quickstart-app[quickstart-app] tutorial.

You can see an example of a *generated repository web application* using gvNIX
http://repository-gvnix.rhcloud.com/login[here] (*user*: admin | *pass*: admin)

== Run from Git

If you want to preview this sample application, follow this steps on the following order. If you prefer to develop by your own, go to https://github.com/DISID/gvnix-samples/tree/master/quickstart-repository-app#build-your-own-repository-app[gvNIX Repository Guide]

- Clone github repository
[source, shell]
$ git clone https://github.com/DISID/gvnix-samples.git

- Acces to quickstart-repository-app
[source, shell]
$ cd quickstart-repository-app

- Execute application using maven:
[source, shell]
$ mvn clean compile tomcat:run

- Open your browser on http://localhost:8080/petclinic/
- Access using _admin_ as username and _admin_ as password.

== Build your own app 	
 	
You can execute https://github.com/DISID/gvnix-samples/blob/master/quickstart-repository-app/quickstart-repository.roo[quickstart-repository.roo] file and creates a petclinic example application with both service and repository layers. 	
 	
If you don't have experience using gvNIX, you can follow https://github.com/DISID/gvnix-samples/tree/master/quickstart-app#build-your-own-app[quickstart-app guide] and then follow the instructions below to generate repository layers and services. 	
 	
This guide teaches you how to: 	

. <<add-repository-functionality-to-entities, Add Repository Functionality to Entities>> 
. <<generate-repository-layer, Generate Repository Layer>> 	
. <<generate-services, Generate Service Layer>> 	
. <<configure-datatables-and-loupes, Configure Datatables And Loupes >> 	

 	
[[add-repository-functionality-to-entities]] 	
== Add Repository Functionality to Entities 	
	
By default Spring Roo uses Active record-style JPA Entities. To opt out of the default Active Record style, you have to create your entities with the activeRecord option set to false.

[source,shell]
entity jpa --class ~.domain.Pet --activeRecord false
entity jpa --class ~.domain.Visit --activeRecord false
entity jpa --class ~.domain.Vet --activeRecord false
entity jpa --class ~.domain.Owner --activeRecord false
entity jpa --class ~.domain.AbstractPerson --activeRecord false

This will add the @RooJpaEntity notation to your entities insted of the @RooJpaActiveRecord notation.

 	
[[generate-repository-layer]] 	
== Generate Repository Layer
 	
Now, you can add the repository layers to your entities. To generate them you have to run the next commands:
	
[source, shell]
repository jpa --interface ~.repository.PetRepository --entity ~.domain.Pet
repository jpa --interface ~.repository.VisitRepository --entity ~.domain.Visit
repository jpa --interface ~.repository.AbstractPersonRepository --entity ~.domain.AbstractPerson
repository jpa --interface ~.repository.VetRepository --entity ~.domain.Vet
repository jpa --interface ~.repository.OwnerRepository --entity ~.domain.Owner

 	
[[generate-services]] 	
== Generate Service Layer	
 	
You can include a service layer in your application. It will expose the CRUD functionality provided by this persistence layer through its interface and implementation. 
To create a service layer for each entity you have to execute the next command, which creates an interface and an implementation of the services: 
	
[source, shell]
service type --interface ~.service.PetService --entity ~.domain.Pet
service type --interface ~.service.VisitService --entity ~.domain.Visit
service type --interface ~.service.AbstractPersonService --entity ~.domain.AbstractPerson
service type --interface ~.service.VetService --entity ~.domain.Vet
service type --interface ~.service.OwnerService --entity ~.domain.Owner

If a persistence-providing layer such as Roo's default entity layer or a repository layer is present for a given domain entity, the service layer will expose the CRUD functionality provided by this persistence layer through its interface and implementation.
In your case, the service layer will call to the repository layer.


[[configure-datatables-and-loupes]] 	
== Configure Datatables And Loupes

Datatables and Loupe field need to access to an entity manager to perform the database operations. But, if you use a repository layer, the entitity manager is not avaliable. To solve this problem you have to follow this steps:

. Create a RepositoryCustom class, in the repository package, using this code:
+
[source,java]
public interface RepositoryCustom {
  public abstract EntityManager getEntityManager();
}
 	
. Create a EntityManagerProviderImpl class which extends EntityManager, in the web package, using this code:
+
[source,java]
public class EntityManagerProviderImpl implements EntityManagerProvider {
	private @Autowired ListableBeanFactory listableBeanFactory;
	public EntityManager getEntityManager(Class klass) {
	    try {
	      Repositories repositories = new Repositories(listableBeanFactory);
	      Object r = repositories.getRepositoryFor(klass);
	      Method[] methods = r.getClass().getDeclaredMethods();
	        for (Method method : methods) {
	                if (method.getReturnType() == EntityManager.class) {
	                    method.setAccessible(true);
	                    return (EntityManager) method.invoke(r, null);
	                }
	        }
	    }
	    catch (Exception e) {
	        throw new IllegalStateException(
	                "Error getting entity manager for domain class: ".concat(klass.getName()), e);
	    }
	    throw new IllegalStateException(
	            "Cannot get entity manager for domain class: ".concat(klass.getName()));
	}
}

. You have to register the correct entityManagerProvider. To do this, in the /petclinic/src/main/webapp/WEB-INF/spring/webmvc-config.xml file, change the class of the entityManagerProvider bean by the EntityManagerProviderImpl location. The result bean will be:
+
[source,xml]
<bean class="com.springsource.petclinic.web.EntityManagerProviderImpl" id="entityManagerProvider"/>

. Change your repository interfaces to make them extend RepositoryCustom:
+
[source,java]
public interface VetRepository extends RepositoryCustom{}
public interface VisitRepository extends RepositoryCustom{}
public interface PetRepository extends RepositoryCustom{}
public interface OwnerRepository extends RepositoryCustom{}
public interface AbstractPersonRepository extends RepositoryCustom {}

. Create a repository implementation class, in the repository package, for every repository interface. These classes extend RepositoryCustom and contain the next code:
+
[source,java]
@PersistenceContext
    private EntityManager em;
    public EntityManager getEntityManager() {
      return em;
}
+
====
*Example*

[source,java]
public class VisitRepositoryImpl implements RepositoryCustom{
    @PersistenceContext
    private EntityManager em;
    public EntityManager getEntityManager() {
      return em;
    }
}
====



== Related libraries, projects, etc..

gvNIX is based on https://github.com/spring-projects/spring-roo[Spring Roo] project. 

http://docs.spring.io/autorepo/docs/spring-roo/1.3.1.RELEASE/reference/html/base-layers.html[Spring Repository Documentation]
